print("Hei, la oss prøve et lite sjakk-quiz!")
print()
print("1. Vi har sluttspillet ♔ ♗ ♘ mot ♚.")
print("Hva blir dette med korrekt spill fra begge parter?")
print("A. Seier til hvit, B. Remis, C. Seier til svart?")
svar = input("Ditt svar: ")
print("Korrekt var A. Du svarte", svar)
print()
print("2. Hva kalles åpningen \u2659e4 - \u265Fc5")
print("A. Carlsen-gambit, B. Siciliansk, C. Russisk?")
svar = input("Ditt svar: ")
print("Korrekt var B. Du svarte", svar)
print('Hvor mange skritt kan kongen ta i ett trekk')
print('A. 3, b. 4, c. 1')
svar=input('Ditt svar: ')
print('Korrekt var C. Du svarte ', svar)
print('Hvilket resultat er mest sansynlig i sjakk?')
print('A. Hvit seier, B. remis(uavgjort), C. Svart seier')
svar=input('Ditt svar: ')
print('Korrekt var B. Du svarte', svar)
print('hvor mange ruter har et sjakkbrett?')
print('A. 64, B. 49, C. 81')
svar=input('Skriv inn ditt svar: ')
print('Korrekt var A. Du svarte ',svar)

